language: java

before_script:
- "Xvfb :99 &"
- "export DISPLAY=:99.0"
- sleep 3 # give xvfb some time to start

script:
- ./gradlew build cucumber

after_success:
- ./gradlew jacocoTestReport coveralls